### PR TITLE
Adds a Travis build status badge

### PR DESCRIPTION
**Pull request by jeffjewiss**

### CODE REVIEW

**Comment by corysimmons** [comment]
@jeffjewiss This looks like it's pointing to https://travis-ci.org/jeffjewiss/broccoli-postcss ?

**Comment by jeffjewiss** [comment]
Yeah sorry, that was a copy/paste fail on my part.

It looks like Travis isn't fully setup anyway, so it's your call if it's something worth having enabled.

Cheers

**Comment by corysimmons** [comment]
I'd love to have Travis integration. Care to PR? :)

**Comment by corysimmons** [comment]
Nevermind, got it working I think.

**Comment by jeffjewiss** [comment]
Awesome! Glad you got it working. :smiley:

**Pull request closed without merging**
